apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgBm1O...
  template:
    metadata:
      name: mysecret
      namespace: default
